### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by razz1618** [cjneely10/MetaSanity#6]
Hi, 
I would like to use Metasanity on my MAG's for annotation. I followed the wiki page for installation. 
I created a conda environment with python 3.6 and successfully pulled the docker files. 
My lab's server does not allow connection to https://raw.githubusercontent.com so manually pulled the metasanity zip file and extracted it within conda environment.
Then I ran python3 /home/mcs/miniconda3/envs/metasanity/MetaSanity/install.py
and got the following error

 python3 /home/mcs/miniconda3/envs/metasanity/MetaSanity/install.py
v0.1.2: Pulling from cjneely10/metasanity
Digest: sha256:7187b60c441925c9e8e0ab2a02291026b47474be2f95d9a929902f907229ba26
Status: Image is up to date for cjneely10/metasanity:v0.1.2
docker.io/cjneely10/metasanity:v0.1.2
Processing /home/mcs/.cache/pip/wheels/b2/45/ec/a1e20f75a05569b7e32e4aba89aa24516e9ad5bf18b0898352/BioMetaDB-0.1.3.0-cp37-cp37m-linux_x86_64.whl
Collecting biopython==1.76
  Using cached biopython-1.76-cp37-cp37m-manylinux1_x86_64.whl (2.3 MB)
Requirement already satisfied: SQLAlchemy==1.3.12 in /home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages (from BioMetaDB==v0.1.3.0) (1.3.12)
Collecting configparser==3.8.1
  Using cached configparser-3.8.1-py2.py3-none-any.whl (22 kB)
Collecting Cython==0.29.14
  Using cached Cython-0.29.14-cp37-cp37m-manylinux1_x86_64.whl (2.1 MB)
Requirement already satisfied: numpy in /home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages (from biopython==1.76->BioMetaDB==v0.1.3.0) (1.17.3)
ERROR: Error while checking for conflicts. Please file an issue on pip's issue tracker: https://github.com/pypa/pip/issues/new
Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3021, in _dep_map
    return self.__dep_map
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3012, in _parsed_pkg_info
    return self._pkg_info
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 520, in _determine_conflicts
    return check_install_conflicts(to_install)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 108, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_internal/operations/check.py", line 50, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dist.requires())
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2736, in requires
    dm = self._dep_map
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3023, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3032, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3014, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1616, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2]No such file or directory: '/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/biopython-1.78.dist-info/METADATA'
Installing collected packages: biopython, configparser, Cython, BioMetaDB
  Attempting uninstall: biopython
    Found existing installation: biopython 1.78
ERROR: Could not install packages due to an EnvironmentError: [Errno 2]**No such file or directory**: '/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/biopython-1.78.dist-info/RECORD'

--2020-12-15 17:05:03--  https://raw.githubusercontent.com/cjneely10/MetaSanity/v0.0.6/Sample/Config/Docker/FuncSanity.ini
Resolving host raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... **Failed: connection denied**.
 raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... **Failed: connection denied**.
Traceback (most recent call last):
  File "/home/mcs/miniconda3/envs/metasanity/MetaSanity/install.py", line 285, in <module>
    locals()[section]()
  File "/home/mcs/miniconda3/envs/metasanity/MetaSanity/install.py", line 255, in docker_installation
    scripts()
  File "/home/mcs/miniconda3/envs/metasanity/MetaSanity/install.py", line 234, in scripts
    config_pull()
  File "/home/mcs/miniconda3/envs/metasanity/MetaSanity/install.py", line 43, in func_wrapper
    func(*args, **kwargs)
  File "/home/mcs/miniconda3/envs/metasanity/MetaSanity/install.py", line 114, in config_pull
    check=True)
  File "/home/mcs/miniconda3/envs/metasanity/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['wget', 'https://raw.githubusercontent.com/cjneely10/MetaSanity/v0.0.6/Sample/Config/Docker/FuncSanity.ini', '-O', 'FuncSanity.ini']' returned non-zero exit status 4.

I guess it is related to the connection problem. Is there any alternate way that I can set up these files?

**Comment by cjneely10** [comment]
Good afternoon,

First off, I apologize for my (incredibly) late response to your issue!

I think there are two things happening here:

1) Definitely a good deal of issues are occurring because of the connection - unfortunately, there are multiple places in the installation script that use `wget` to access `https://raw.githubusercontent.com`. Currently the installation script is the most straightforward way to gather all of the files.

That being said, *technically* the script only automates a few steps:

```
git clone https://github.com/cjneely10/MetaSanity.git
cd MetaSanity
git checkout v0.0.6
pip3 install -r requirements.txt
python3 setup.py build_ext --inplace
docker pull cjneely10/metasanity:v0.1.2
```

Note that the config files you will use in your analyses will be located in:

```
MetaSanity/Sample/Config/Docker
```

(this will make more sense as the program is used)


Test data set will be located in 

```
MetaSanity/Example-Genomes-Set
```

From here, you **should** be able to complete the rest of the installation steps on the wiki page (beginning at Step Three).
You will need to comment-out line 110 in the `download-data.py` script prior to running it.

```
# wget(MEROPS_AS_PFAMS_URL, "merops-as-pfams.txt")
```

Finally, manually copy the datafile from

```
MetaSanity/Sample/Data/merops-as-pfams.txt
```

into the `databases/peptidase` folder that is generated by running the script.


2) There appears to be an error when installing python requirements. Internally, the `install.py` script runs the following command from within the downloaded MetaSanity github repo:

```
pip3 install -r requirements.txt
```

Since you mentioned you are using a python3.6 environment, your output suggests that python3.7 is getting mixed into the installation step somehow:

```
File "/home/mcs/miniconda3/envs/vibrant/lib/python3.7/site-packages/pip/_vendor/pkg_resources/init.py", line 2815, in getattr
raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
```

There may be some environment issue that is causing this to happen. I would suggest creating a virtual environment using `venv`  and trying from there.



Once again, I apologize for the late response. Feel free to let me know if you need any clarification or if there are any other issues!

- Chris
