### ISSUE TITLE
Issue when running FuncSanity

### ISSUE THREAD

**Issue by BenLRoss** [cjneely10/MetaSanity#7]
MetaSanity Version: v1.3.0
Installation Type: Conda
Installed using `install.py`?: No
Databases downloaded using `download-data.py`?: No
Using a python virtual environment or conda?: Conda

Hello,

I ran MetaSanity after installing it with no issues and making it callable, and I had received these errors after attempting to run FuncSanity on a set of genomes: 

```
Traceback (most recent call last):
  File "/media/imperator/bross/MetaSanity/pipedm.py", line 67, in <module>
    pc.run(ap.args, debug=True)
  File "MetaSanity/Accessories/program_caller.pyx", line 137, in MetaSanity.Accessories.program_caller.ProgramCaller.run
    self.mapper(program, debug)
  File "MetaSanity/Accessories/program_caller.pyx", line 109, in MetaSanity.Accessories.program_caller.ProgramCaller.mapper
    return self.programs[program](**self.flags_dict)
  File "MetaSanity/Pipeline/metagenome_annotation.pyx", line 77, in MetaSanity.Pipeline.metagenome_annotation.metagenome_annotation
    genome_list_path, alias, table_name, cfg, biometadb_project = project_check_and_creation(
  File "MetaSanity/PipelineManagement/project_manager.pyx", line 30, in MetaSanity.PipelineManagement.project_manager.project_check_and_creation
    assert os.path.isdir((<object>directory)) and os.path.isfile((<object>config_file)), \
AssertionError: Invalid parameters passed
Traceback (most recent call last):
  File "/media/imperator/bross/bin/MetaSanity", line 386, in <module>
    check=True,
  File "/media/imperator/bross/miniconda3/envs/MetaSanity/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '/media/imperator/bross/MetaSanity/pipedm.py', 'FuncSanity', '-d', 'bioaerosols_prokaryotes_final/genomes', '-o', 'bioaerosols_prokaryotes_final/FuncSanity', '-c', 'bioaerosols_prokaryotes_final/FuncSanity/FuncSanity.ini', '-t', '.fa', '-a']' returned non-zero exit status
```

I was wondering if the issue arose out of making MetaSanity callable? I had originally chose to do so because I was unable to run FuncSanity in the environment with the command from the wiki page and had to run the command via activating `MetaSanity.py` with the `python` command. Now the typical MetaSanity FuncSanity command formula works, but I get this error.

**Comment by cjneely10** [comment]
Hi @BenLRoss,

Sorry about the confusion (and about the highly unhelpful error statement). Can you confirm that the output directory provided with the `-o` flag matches the output directory that you used when running PhyloSanity?

Chris

**Comment by BenLRoss** [comment]
I hadn't run PhyloSanity, but I just attempted it and very similar error messages were produced:
```Traceback (most recent call last):
  File "/media/imperator/bross/MetaSanity/pipedm.py", line 67, in <module>
    pc.run(ap.args, debug=True)
  File "MetaSanity/Accessories/program_caller.pyx", line 137, in MetaSanity.Accessories.program_caller.ProgramCaller.run
    self.mapper(program, debug)
  File "MetaSanity/Accessories/program_caller.pyx", line 109, in MetaSanity.Accessories.program_caller.ProgramCaller.mapper
    return self.programs[program](**self.flags_dict)
  File "MetaSanity/Pipeline/metagenome_evaluation.pyx", line 44, in MetaSanity.Pipeline.metagenome_evaluation.metagenome_evaluation
    genome_list_path, alias, table_name, cfg, biometadb_project = project_check_and_creation(
  File "MetaSanity/PipelineManagement/project_manager.pyx", line 30, in MetaSanity.PipelineManagement.project_manager.project_check_and_creation
    assert os.path.isdir((<object>directory)) and os.path.isfile((<object>config_file)), \
AssertionError: Invalid parameters passed
Traceback (most recent call last):
  File "/media/imperator/bross/MetaSanity/build/MetaSanity.py", line 386, in <module>
    check=True,
  File "/media/imperator/bross/miniconda3/envs/MetaSanity/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '/media/imperator/bross/MetaSanity/pipedm.py', 'PhyloSanity', '-d', 'bioaesorols_prokaryotes_final/genomes', '-o', 'bioaesorols_prokaryotes_final/PhyloSanity', '-c', 'bioaerosols_prokaryotes_final/PhyloSanity/PhyloSanity.ani', '-t', '.fa', '-a']' returned non-zero exit status 1.

**Comment by cjneely10** [comment]
Hi @BenLRoss,

Are you able to run the example analysis that is provided with the installation without issues? If so, can you try `cd`-ing into your top-level analysis directory prior to running?

**Comment by BenLRoss** [comment]
I tried running the example analysis with PhyloSanity in the MetaSanity directory and I get similar AssertionError messages:

```Traceback (most recent call last):
  File "/media/imperator/bross/MetaSanity/pipedm.py", line 67, in <module>
    pc.run(ap.args, debug=True)
  File "MetaSanity/Accessories/program_caller.pyx", line 137, in MetaSanity.Accessories.program_caller.ProgramCaller.run
    self.mapper(program, debug)
  File "MetaSanity/Accessories/program_caller.pyx", line 109, in MetaSanity.Accessories.program_caller.ProgramCaller.mapper
    return self.programs[program](**self.flags_dict)
  File "MetaSanity/Pipeline/metagenome_evaluation.pyx", line 44, in MetaSanity.Pipeline.metagenome_evaluation.metagenome_evaluation
    genome_list_path, alias, table_name, cfg, biometadb_project = project_check_and_creation(
  File "MetaSanity/PipelineManagement/project_manager.pyx", line 30, in MetaSanity.PipelineManagement.project_manager.project_check_and_creation
    assert os.path.isdir((<object>directory)) and os.path.isfile((<object>config_file)), \
AssertionError: Invalid parameters passed
Traceback (most recent call last):
  File "/media/imperator/bross/bin/MetaSanity", line 386, in <module>
    check=True,
  File "/media/imperator/bross/miniconda3/envs/MetaSanity/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '/media/imperator/bross/MetaSanity/pipedm.py', 'PhyloSanity', '-d', 'genomes', '-o', 'out', '-c', 'PhyloSanity.ini', '-t', 'None', '-a']' returned non-zero exit status 1.
```

Is the issue arising out of making MetaSanity callable?

**Comment by cjneely10** [comment]
I don't think it had to do with making MetaSanity callable. It seems that the issue is more with its start-up process, though I must admit that I am a bit unsure why this error is occurring.

The key line is:

```
assert os.path.isdir((<object>directory)) and os.path.isfile((<object>config_file))
```

Which is a check to make sure that the directory you provided exists (and is a directory) and that the config file you provided also exists (and is a file).

Since I'm guessing these are both true, there are a couple things to double-check:

- The working directory is not the same as the installation directory.
- There are no other installations of MetaSanity on your system/user profile that may be causing linking issues.

**Comment by BenLRoss** [comment]
I removed and reinstalled MetaSanity, made sure there was only one installation and one Conda environment for it, didn't make it callable, and attempted running PhyloSanity on a new directory for my prokaryote annotation. A new error appears, and now it seems to be a path issue, potentially In the .ini file?


```
PATH for FASTANI not found
Traceback (most recent call last):
  File "/media/imperator/bross//MetaSanity/build/MetaSanity.py", line 386, in <module>
    check=True,
  File "/media/imperator/bross/miniconda3/envs/MetaSanity/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python3', '/media/imperator/bross/MetaSanity/pipedm.py', 'PhyloSanity', '-d', '../prokaryote_annotation/genomes', '-o', '../prokaryote_annotation/PhyloSanity', '-c', '../prokaryote_annotation/PhyloSanity/PhyloSanity.ini', '-t', 'None', '-a']' returned non-zero exit status 1.
```

**Comment by BenLRoss** [comment]
Also attempted with the `Example-Genomes-Set` and the same error message was returned.
